version: '3'
services:
  redis-server:
    image: 'redis'
    container_name: redis
    ports:
      - "6379:6379"
  rest-api-app:
    build: .
    container_name: sharks-api
    ports:
      - "5050:5050"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
