version: '3'
services:
  redis-server:
    image: 'redis'
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
  rest-api-app:
    build: .
    container_name: sharks-api
    volumes:
      - /media/external:/media/external
    ports:
      - "5050:5050"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: unless-stopped
